### ISSUE TITLE
Timeout triggered on new SSH workspace having nodejs v6.4.0

### ISSUE THREAD

**Issue by budinschi** [c9/install#74] opened 2016-08-18 22:40 UTC
I'm getting a "Timeout" error message when trying to create a new SSH workspace. I've looked at into a workspace I successfully created a week ago, and I realized that I'm running nodejs 6.3.1 on that server.
On the current server, I downgraded nodejs from v6.4 to v6.3.1, and successfully proceeded with a new workspace installation. Problem solved after noticing the different version.
Cheers

**Comment by nightwing** [comment] 2016-08-20 00:06
This is caused by https://github.com/nodejs/node/pull/7494/files, which broke the version of msgpack-js we were using. Unfortunately we can't update it since the next version have introduced 2x performance regression. but we are working on a fix now. Thanks for reporting this issue!

**Comment by nightwing** [comment] 2016-08-26 16:33
This is fixed by https://github.com/c9/core/commit/18f7963e2cd3abd02ef7c3d53f7c30d6623e7f10, thanks for the report!

**Closed by nightwing** 2016-08-26 16:33 UTC
